on:
  pull_request: ~
  push:
    branches: ['*.x']

jobs:
  composer-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - run: |
          composer validate --strict --ansi --no-check-publish
          composer validate --strict --ansi src/Reflection/composer.json
          composer validate --strict --ansi src/Type/composer.json
          composer validate --strict --ansi src/TypeStringifier/composer.json

  composer-normalize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --optimize-autoloader
      - run: |
          composer normalize --dry-run --diff --ansi
          composer normalize --dry-run --diff --ansi src/Reflection/composer.json
          composer normalize --dry-run --diff --ansi src/Type/composer.json
          composer normalize --dry-run --diff --ansi src/TypeStringifier/composer.json

  php-cs-fixer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, cs2pr
          coverage: none
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --optimize-autoloader
      - run: vendor/bin/php-cs-fixer fix -v --dry-run --format=checkstyle --ansi | cs2pr
      - run: vendor/bin/php-cs-fixer fix -v --dry-run --format=checkstyle --ansi --config=.sort-reflection-elements.php-cs-fixer.dist.php | cs2pr

  psalm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --optimize-autoloader
      - run: composer psalm -- --php-version=${{ matrix.php }} --stats --output-format=github

  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --optimize-autoloader
      - run: composer phpstan

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --optimize-autoloader
      - run: composer test -- --colors=always --order-by=random
