on:
  push:
    branches: ['*.x']

jobs:
  split:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: |
          git config --global user.name 'Typhoon Splitter'
          git config --global user.email splitter@typhoon.php
          git subtree push --prefix src/Type https://${{ secrets.SPLITTER_ACCESS_TOKEN }}@github.com/typhoon-php/type-split.git ${{ github.ref_name }}
          git subtree push --prefix src/TypeStringifier https://${{ secrets.SPLITTER_ACCESS_TOKEN }}@github.com/typhoon-php/type-stringifier-split.git ${{ github.ref_name }}
          git subtree push --prefix src/Reflection https://${{ secrets.SPLITTER_ACCESS_TOKEN }}@github.com/typhoon-php/reflection-split.git ${{ github.ref_name }}
